apiVersion: v1
kind: ServiceAccount
metadata:
  name: aipower-collector-sa
  namespace: finops
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aipower-collector-role
rules:
  - apiGroups: [""]
    resources: ["pods", "nodes", "events"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["resources.k8s.io", "metrics.k8s.io"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: aipower-collector-rolebinding
subjects:
  - kind: ServiceAccount
    name: aipower-collector-sa
    namespace: finops
roleRef:
  kind: ClusterRole
  name: aipower-collector-role
  apiGroup: rbac.authorization.k8s.io
