server:
  addr: ":8080"

redis:
  addr: "10.8.8.55:6379"
  password: "difyai123456"
  db: 0

mysql:
  dsn: "qxw:Gaoji_001#@tcp(10.8.132.147:3306)/aipower?parseTime=true"

prometheus:
  url: "http://localhost:9090"

k8s:
  kubeconfig: "" # 本地调试如果不填，则默认寻找 ~/.kube/config
